### ISSUE TITLE
Role - Desired Action - Benefit

### ISSUE THREAD

**Issue by graybeal** [i-adopt/users_stories#2]
See https://github.com/i-adopt/users_stories/blob/master/README.md for help filling out this template.

## As a...
Specify your role or the user's role (e.g. As a scientist, or as a data analyst, etc.) 

## I want to...
Specify the action you or the user want to perform 

## So that...
Specify why the actions needs to be performed, for what result, for what benefit

## Domain(s)
Specify what domain or what multiple domains need to be covered for that particular user story

## Addition Information
You may add other information about your user story here, including more detailed descriptions of the problem(s).

**Comment by jonquet** [comment]
@mabablue I think this issue can be closed/delete.  This was a test from @graybeal
